# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74ad54e7308d096f3e5be60a39cab6d81c93ad73e7d7c92225f77b7a466c947478db62833cfd06111adf091885ce973f1100780284e85e9b14ff1bc0425ed72f

test:
  secret_key_base: 6e35fbb510ad892ac0901f0d162d39a36e14b793450f0d61659f796c8dc10b7ed20a61605acf23e72a607fb671dec674affbeb354e32a232e7b44dc1e4b1fd92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
